
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

public class VistaModificarEvento extends javax.swing.JFrame {
    private ArrayList<Lugar> lugares;
    // Constructor de la ventana
    public VistaModificarEvento(ArrayList<Lugar> lugares) {
        this.lugares = lugares;
        initComponents();
        
        // Se crea un modelo para el ComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 0; i < lugares.size(); i++)
        {
            // Se agrega cada lugar (Su nombre) al modelo
            model.addElement(lugares.get(i).getNombre());
        }
        // Se asigna dicho modelo al ComboBox en el JFrame
        jComboBoxLugares.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLugar = new javax.swing.JLabel();
        jComboBoxLugares = new javax.swing.JComboBox<>();
        LabelEvento = new javax.swing.JLabel();
        jComboBoxEventos = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        labelCAsistentes = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCAsistentes = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLugar.setText("¿En qué lugar quieres modificar?");

        jComboBoxLugares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLugaresActionPerformed(evt);
            }
        });

        LabelEvento.setText("¿Qué evento quieres modificar?");

        jComboBoxEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEventosActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre");

        labelCAsistentes.setText("Cantidad de asistentes");

        labelTipo.setText("Tipo de evento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLugar)
                            .addComponent(LabelEvento)
                            .addComponent(labelNombre)
                            .addComponent(labelCAsistentes)
                            .addComponent(labelTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxLugares, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCAsistentes)
                            .addComponent(txtNombre)
                            .addComponent(jComboBoxEventos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipo))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLugar)
                    .addComponent(jComboBoxLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEvento)
                    .addComponent(jComboBoxEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCAsistentes)
                    .addComponent(txtCAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLugaresActionPerformed
        // TODO add your handling code here:
        int num = jComboBoxLugares.getSelectedIndex();
        Lugar lugar = lugares.get(num);
        String ss = lugar.listarEventosNombre();
        String[] arr = ss.split("\n");
        // Se crea un modelo para el ComboBox
        DefaultComboBoxModel<String> modelEventos = new DefaultComboBoxModel<>();
        for (int i = 0; i < arr.length; i++)
        {
            // Se agrega cada evento (Su nombre) al modelo
            modelEventos.addElement(arr[i]);
        }
        // Se asigna dicho modelo al ComboBox en el JFrame
        jComboBoxEventos.setModel(modelEventos);
    }//GEN-LAST:event_jComboBoxLugaresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Se cierra la ventana sin hacer cambios.
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jComboBoxEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEventosActionPerformed
        // TODO add your handling code here:
        // Al seleccionar un evento, se establece en los TextFields los valores de este.
        String nEvento = (String)jComboBoxEventos.getSelectedItem();
        int num = jComboBoxLugares.getSelectedIndex();
        txtNombre.setText(lugares.get(num).getEvento(nEvento).getNombre());
        txtCAsistentes.setText(String.valueOf(lugares.get(num).getEvento(nEvento).getAsistentes()));
        txtTipo.setText(lugares.get(num).getEvento(nEvento).getTipo());
    }//GEN-LAST:event_jComboBoxEventosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Al presionar el boton de guardar, cambia los valores del evento en el lugar
        int num = jComboBoxLugares.getSelectedIndex();
        Lugar lugar = lugares.get(num);
        String nombreOriginal = lugares.get(num).getEvento((String)jComboBoxEventos.getSelectedItem()).getNombre();
        lugar.modificarEvento(txtNombre.getText(), Integer.parseInt(txtCAsistentes.getText()), txtTipo.getText(), nombreOriginal);
        
        
        this.dispose(); // Se cierra la ventana
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEvento;
    private javax.swing.JLabel LabelLugar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBoxEventos;
    private javax.swing.JComboBox<String> jComboBoxLugares;
    private javax.swing.JLabel labelCAsistentes;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField txtCAsistentes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
